env: 
    CIRRUS_CLONE_DEPTH: 1

task:
    name: builds
    timeout_in: 120m
    container:
      image: mhmmdfdlyas/dockerfile:r
      cpu: 8
      memory: 32G      

    test_script:
      - gd_id="1BfmxF_m1UsZvrRf66vs85YNK8fQ6egzK"
      - wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=$gd_id' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=$gd_id" -O ccache.tar.gz  && rm -rf /tmp/cookies.txt
      - time tar xf ccache.tar.gz && rm -rf ccache.tar.gz
      - mkdir -p ~/.config/rclone
      - wget -O rclone.conf https://pastebin.com/raw/saPEwjhS
      - mv rclone.conf ~/.config/rclone/
      - mkdir -p /tmp/cirrus-ci-build/main_dir
      - export CCACHE_DIR=/tmp/cirrus-ci-build/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 50G
      - ccache -o compression=true
      - ccache -z
      - bash sinkronisasi
      - bash membangun_akhir
