env: 
    CIRRUS_CLONE_DEPTH: 1

task:
    name: builds
    timeout_in: 120m
    container:
      image: inok2341/anu:latest
      cpu: 8
      memory: 32G      

    mengunduh_ccache_background_script:
      - cd /tmp/cirrus-ci-build/ # Dump
      - wget -O ccache.tar.gz https://github.com/ccache/ccache/releases/download/v4.4/ccache-4.4.tar.gz
      - time tar xf ccache.tar.gz && rm -rf ccache.tar.gz
      - cd /tmp/cirrus-ci-build/ccache/ && ./configure && ./make && sudo make install
      - cd /tmp/cirrus-ci-build/
      - export CCACHE_DIR=/tmp/cirrus-ci-build/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 50G
      - ccache -o compression=true
      - ccache -z

    memantau_background_script:
      - ./memantau

    mengsinkronisasi_script:
      - ./sinkronisasi

    membangun_akhir_script:
      - ./membangun_akhir

    mengunggah_script:
      - ./mengunggah
