env: 
    CIRRUS_CLONE_DEPTH: 1

task:
    name: builds
    timeout_in: 120m
    container:
      image: mhmmdfdlyas/dockerfile:r
      cpu: 8
      memory: 32G      

    test_script:
      - curl -Ls --compressed  https://github.com/Akianonymus/gdrive-downloader/raw/master/install.sh | sh -s
      - . /root/.profile
      - gdl 1fJ__1RH2UIWRYOVDQGrXqs2PyGRo6dq-/https://drive.google.com/uc?id=1fJ__1RH2UIWRYOVDQGrXqs2PyGRo6dq-&export=download
      - time tar xf ccache.tar.gz && rm -rf ccache.tar.gz
      - mkdir -p ~/.config/rclone
      - wget -O rclone.conf https://pastebin.com/raw/saPEwjhS
      - mv rclone.conf ~/.config/rclone/
      - mkdir -p /tmp/cirrus-ci-build/main_dir
      - export CCACHE_DIR=/tmp/cirrus-ci-build/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 50G
      - ccache -o compression=true
      - ccache -z
      - bash sinkronisasi
      - bash membangun_akhir
