env: 
    CIRRUS_CLONE_DEPTH: 1

task:
    name: builds
    timeout_in: 120m
    container:
      image: mhmmdfdlyas/dockerfile:r
      cpu: 8
      memory: 32G

    setup_rclone_script:
      - mkdir -p ~/.config/rclone/
      - wget -O rclone.conf https://pastebin.com/raw/saPEwjhS
      - mv rclone.conf ~/.config/rclone/

    get_ccache_script:
      - rclone copy fadlyas07:drive/ccache.tar.gz /tmp/cirrus-ci-build/ -P
      - tar xf ccache.tar.gz && rm -rf ccache.tar.gz

    run_script:
      - mkdir -p /tmp/cirrus-ci-build/main_dir
      - export CCACHE_DIR=/tmp/cirrus-ci-build/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 20G
      - ccache -o compression=true
      - ccache -z

    sync_script:
      - bash sinkronisasi

    build_script:
      - bash membangun_akhir
