env: 
    CIRRUS_CLONE_DEPTH: 1

task:
    name: builds
    timeout_in: 120m
    container:
      image: mhmmdfdlyas/dockerfile:r
      cpu: 8
      memory: 32G      

    ccache_script:
      - cd ~/
      - curl -Ls --compressed https://github.com/Akianonymus/gdrive-downloader/raw/master/install.sh | sh -s
      - . /root/.profile
      - gdl 1qQVJpMmsR2m_m0QwRGDSeKtBKXBUkDnO/https://drive.google.com/u/0/uc?id=1qQVJpMmsR2m_m0QwRGDSeKtBKXBUkDnO&export=download

    download_ccache_script:
      - cd ~/
      - time tar xf ccache.tar.gz && rm -rf ccache.tar.gz
      - mv ccache /tmp/cirrus-ci-build/
      - cd /tmp/cirrus-ci-build/

    setup_rclone_script:
      - mkdir -p ~/.config/rclone
      - wget -O rclone.conf https://pastebin.com/raw/saPEwjhS
      - mv rclone.conf ~/.config/rclone/

    run_script:
      - mkdir -p /tmp/cirrus-ci-build/main_dir
      - export CCACHE_DIR=/tmp/cirrus-ci-build/ccache
      - export CCACHE_EXEC=$(which ccache)
      - export USE_CCACHE=1
      - ccache -M 50G
      - ccache -o compression=true
      - ccache -z
      - bash sinkronisasi
      - bash membangun_akhir
