task:
    name: meh
    timeout_in: 120m
    container:
      image: mhmmdfdlyas/dockerfile:r
      cpu: 8
      memory: 32G
    setup_rclone_script:
      - mkdir -p ~/.config/rclone/
      - wget -O rclone.conf https://pastebin.com/raw/saPEwjhS
      - mv rclone.conf ~/.config/rclone/
      - rclone copy fadlyas07:drive/ccache.tar.gz /tmp/cirrus-ci-build/ -P
      - tar xf ccache.tar.gz && rm -rf ccache.tar.gz
      - echo make main dir before continue to the next task
      - mkdir -p /tmp/cirrus-ci-build/main_dir && echo done, main dir already created ...
    sync_script:
      - bash sinkronisasi
    build_script:
      - bash membangun_akhir
