#!/bin/bash

cd /tmp/cirrus-ci-build/main_dir

export CCACHE_DIR=/tmp/cirrus-ci-build/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G -F 0
ccache -o compression=true
ccache -z
ccache -s
export USER=CarbonOS
export HOSTNAME=greenforce-project

rm -rf device/generic/art device/generic/common device/google/cuttlefish device/google/cuttlefish_prebuilts
w_ccache="$1"
. build/envsetup.sh
lunch carbon_juice-userdebug
if [[ "$w_ccache" != "1" ]] ; then
    make carbon -j$(nproc --all)
    rclone copy "$(echo out/target/product/juice/CR-10.0-S-UNOFFICIAL-juice*.zip)" fadlyas07:drive -P
else
    ccache -M 8G -F 0
    make carbon -j$(nproc --all) &
    sleep 100m
    kill %1
fi
ccache -s

cd ..
name="ccache.tar.gz"
tar -czf "$name" ccache
rclone copy ccache.tar.gz fadlyas07:drive -P
