#!/bin/bash


cd /tmp/cirrus-ci-build/main_dir

find_target=$(find CARBON*juice*.zip)
zip_path=/tmp/cirrus-ci-build/main_dir/out/target/product/juice/${find_target}
curl -sL https://git.io/file-transfer | sh && ./transfer wet "$zip_path" >> link
sleep 2
echo "Download Link: $(cat link)"
